
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const LOAD_NOTES_SUCCESS = 'LOAD_NOTES_SUCCESS';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const GET_ALL_STATE = 'GET_ALL_STATE';
